name: Check Status
on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
  
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Check Status
        run: |
          rm -fr *
          wget https://download.dnscrypt.info/dnscrypt-resolvers/json/public-resolvers.json
          cat public-resolvers.json | grep -B 18 -A 2 '"proto": "DNSCrypt"' | grep -B 6 -A 14 '"dnssec": true,' | grep -B 14 -A 6 '"nolog": true,' | grep -B 7 -A 13 '"ipv6": false,' | grep '"name":' | grep -v 'family' | grep -v 'cleanbrowsing' | grep -v 'adguard' | grep -v 'sfw' | grep -v 'nogoogle' | sed 's/"//g' | sed 's/,//g' | awk '{print $NF}' | tee NoFilter.txt
          cat public-resolvers.json | grep -B 18 -A 2 '"proto": "DNSCrypt"' | grep -B 6 -A 14 '"dnssec": true,' | grep -B 13 -A 7 '"nofilter": false,' | grep -B 14 -A 6 '"nolog": true,' | grep -B 7 -A 13 '"ipv6": false,' | grep '"name":' | grep -v 'family' | grep -v 'cleanbrowsing' | grep -v 'adguard' | grep -v 'sfw' | grep -v 'nogoogle' | sed 's/"//g' | sed 's/,//g' | awk '{print $NF}' | tee Filter.txt
          wget https://download.dnscrypt.info/status/public-resolvers.txt
          cat NoFilter.txt | while read line
          do
          grep $line public-resolvers.txt | sed -e '/ipv6/d' -e '/doh/d' -e '/v6/d' >> NoFilters.txt
          done
          cat Filter.txt | while read line
          do
          grep $line public-resolvers.txt | sed -e '/ipv6/d' >> Filters.txt
          done 
          sort -u NoFilters.txt | tee NoFilterPass.txt
          sort -u Filters.txt | tee FilterPass.txt
          rm -rf public-resolvers.json public-resolvers.txt NoFilters.txt Filters.txt
          mkdir -p .github/workflows
          wget -qO .github/workflows/main.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/main.yml &> /dev/null
          git config --global init.defaultBranch main
          git init
          git add .
          git config user.name "jadeza"
          git config user.email "135102978+jadeza@users.noreply.github.com"
          git commit -m "check"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push origin main --force           
